# Generated by Django 5.0.1 on 2024-01-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
